#!/usr/bin/env bash
cd $HOME/code/boilerplate/app

session="bpdev"

tmux new-session -d -s $session

window=1
tmux rename-window -t $session:$window 'code'
tmux send-keys -t $session:$window 'nvim .' C-m

window=2
tmux new-window -t $session:$window -n 'term'

window=3
tmux new-window -t $session:$window -n 'server'
tmux send-keys -t $session:$window 'docker-compose up' C-m

window=4
tmux new-window -t $session:$window -n 'iex'
tmux send-keys -t $session:$window 'iex' C-m

window=1
tmux attach-session -t $session:$window
