#!/usr/bin/bash

query=$(urlencode "$@")
# url="https://lite.duckduckgo.com/lite?q=$query"
url="https://lite.duckduckgo.com/lite?kd=-1&kp=-1&q=$query"
w3m auto_image=FALSE $url
# w3m auto_image=FALSE https://google.com
