#!/usr/bin/bash


#!/usr/bin/env bash

filename=""

cd $HOME/notes
if [ $# -eq 0 ]
  then
    filename="$(rg '\d{14} ' | fzf | cut -d':' -f1)"
  else
    filename="$(rg '\d{14} ' | fzf --filter '$1' | cut -d':' -f1)"
fi

nvim "$HOME/notes/$filename"


# files=`grep "$1" * 2>/dev/null | cut -d":" -f1 | sort -u`
# echo "$files" | nl
# read -p "Select :" option; 
# rg "\d{14} " | fzf | tee | awk '{gsub(":#", "",$1); x=""; for(i=3; i<=NF; i++) x= x == ""? $i : sprintf("%s-%s",x,$i); print "["x"]""("$1")"}'
