#!/usr/bin/bash

name=`date "+%Y%m%d%H%M%S"`
todo_template="# $name TODO: $(date '+%a %d, %b %Y')

- [ ] Freelance
  - [ ] 
- [ ] Job
  - [ ] 
- [ ] Self
  - [ ] "


printf '%s' "$todo_template" > /tmp/tmp-todo
nvim  -c "r /tmp/tmp-todo" -c "normal za7jA" -c "startinsert!" $HOME/notes/$name.md
